name: Update README

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install PyGithub requests Pillow

      - name: Update README
        env:
          ACCESS_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python3 ./.github/workflows/update_readme.py
